In [6]:
import torch

In [3]:
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())

1.13.1+cu117
True
1


In [13]:
x = torch.randn(4, 4)

In [14]:
y = x.view(16)
z = x.view(-1, 8)
u = x.view(2, 8)

In [17]:
# 当 CUDA 可用的时候，可用运行下方这段代码，采用 torch.device() 方法来改变 tensors 是否在 GPU 上进行计算操作
if torch.cuda.is_available():
    device = torch.device("cuda")          # 定义一个 CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 显示创建在 GPU 上的一个 tensor
    x = x.to(device)                       # 也可以采用 .to("cuda") 
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # .to() 方法也可以改变数值类型
    print(z.to("cpu", torch.float32))

tensor([[ 1.0763,  1.2141,  0.8093, -0.7074],
        [ 0.0920,  0.0139,  1.4872,  1.5422],
        [ 2.4394,  0.3786,  1.7222,  0.8502],
        [ 1.0135,  1.8577,  2.9479,  1.6265]], device='cuda:0')
tensor([[ 1.0763,  1.2141,  0.8093, -0.7074],
        [ 0.0920,  0.0139,  1.4872,  1.5422],
        [ 2.4394,  0.3786,  1.7222,  0.8502],
        [ 1.0135,  1.8577,  2.9479,  1.6265]], dtype=torch.float64)
tensor([[ 1.0763,  1.2141,  0.8093, -0.7074],
        [ 0.0920,  0.0139,  1.4872,  1.5422],
        [ 2.4394,  0.3786,  1.7222,  0.8502],
        [ 1.0135,  1.8577,  2.9479,  1.6265]])
